FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# # Copy your code (optional, can also mount via ProcessingInput)
# COPY . .

# Set default command (not strictly needed for SageMaker Processing)
CMD ["python3"]
